services:
  backend:
    build: ./backend-java
    ports:
      - "3000:3000"
    networks:
      - calculator-network

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - calculator-network

networks:
  calculator-network:
    driver: bridge
